name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  PHP82: '8.2.3'
  PHP81: '8.1.16'
  PHP80: '8.0.28'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  php82:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '8'
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP82 }}
        tags: 8.2,8,latest
        workdir: 8
        platform: linux/amd64,linux/arm64
#  php81:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP81 }}
#        tags: 8.1
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  php80:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP80 }}
#        tags: '8.0'
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  ### dev
#  php82-dev:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP82 }}
#        dev: 1
#        tags: 8.2-dev,8-dev,dev
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  php81-dev:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP81 }}
#        dev: 1
#        tags: 8.1-dev
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  php80-dev:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP80 }}
#        dev: 1
#        tags: 8.0-dev
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  ### dev-macos
#  php82-dev-macos:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP82 }}
#        dev: 1
#        user_id: 501
#        group_id: 20
#        tags: 8.2-dev-macos,8-dev-macos,dev-macos
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  php81-dev-macos:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP81 }}
#        dev: 1
#        user_id: 501
#        group_id: 20
#        tags: 8.1-dev-macos
#        workdir: 8
#        platform: linux/amd64,linux/arm64
#  php80-dev-macos:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: '8'
#    steps:
#    - uses: actions/checkout@v2
#    - uses: docker/setup-qemu-action@v1
#      with:
#        platforms: linux/amd64,linux/arm64
#    - uses: docker/setup-buildx-action@v1
#    - uses: ./.github/actions
#      with:
#        version: ${{ env.PHP80 }}
#        dev: 1
#        user_id: 501
#        group_id: 20
#        tags: 8.0-dev-macos
#        workdir: 8
#        platform: linux/amd64,linux/arm64
